name: wifi_sesli_arama
description: Wi-Fi üzerinden yerel sesli arama uygulaması.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Anlık mikrofon sesini akış (stream) olarak alıp-vermek için
  sound_stream: ^0.3.0
  
  # Kullanıcıdan mikrofon ve ağ izinlerini ekranda istemek için
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
