name: video_player_app  # İstersen adını chat_app yapabilirsin ama şart değil
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Video player'ı kaldırdık, yerine WebSocket ekledik:
  web_socket_channel: ^3.0.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Eğer yerel resim/asset kullanmayacaksan assets kısmını silebilirsin.
  
